services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU20-ubuntu-22.04
    container_name: sqlserver
    ports:
      - "1433:1433"
    env_file:
      - .env.docker
    volumes:
      - ./init-db/init.sql:/db/init.sql
      - ./init-db/entrypoint.sh:/entrypoint.sh
      - sqlserver_data:/var/opt/mssql
    entrypoint: ["/bin/bash", "/entrypoint.sh"]

volumes:
  sqlserver_data:
