[project]
name = "notify-build-stop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosmtpd>=1.4.6",
    "httpx>=0.28.1",
    "pyodbc>=5.2.0",
]

[dependency-groups]
dev = [
    "ruff>=0.12.4",
]
